bridges = []
persistence_dir = ''
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'hc-alice'
keystore_file = './alice.keystore'
name = 'alice'
public_address = 'HcSCJkIYadk9gyciupQpvEp9qgYzcey98K8Fs4JNTjPxn36xV477mCJRckSfpjz'

[[agents]]
id = 'hc-bob'
keystore_file = './bob.keystore'
name = 'bob'
public_address = 'HcScj5cMYmb3WgbrerTvMRaS6Fiewabf9IhUXuwsh89trqnuASGOuzU8Eaktw5r'

[[dnas]]
file = '/home/holomachine/projects/hUdemy/dna/dist/dna.dna.json'
hash = 'QmQo7AGKG5n3NnBs4ZUZN9pP5FHho3PRvePMPRoM2vhhfu'
id = 'hc-courses'

[[instances]]
agent = 'hc-alice'
dna = 'hc-courses'
id = 'alice-instance'

[instances.storage]
type = 'memory'

[[interfaces]]
admin = true
id = 'alice-interface'

[[interfaces.instances]]
id = 'alice-instance'

[interfaces.driver]
port = 8888
type = 'websocket'

[[instances]]
agent = 'hc-bob'
dna = 'hc-courses'
id = 'bob-instance'

[instances.storage]
type = 'memory'

[[interfaces]]
admin = true
id = 'bob-interface'

[[interfaces.instances]]
id = 'bob-instance'

[interfaces.driver]
port = 8889
type = 'websocket'

[logger]
state_dump = true
type = 'debug'

[logger.rules]
rules = []

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = false
trace = false
