bridges = []
persistence_dir = ''
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'hc-alice'
keystore_file = './alice.keystore'
name = 'alice'
public_address = 'HcSCJ5JWB7yrp9ro8tuNoaJRVR7mscd4x7OjxD7HO34r49CtkTCATXji85p8u3z'

[[agents]]
id = 'hc-bob'
keystore_file = './bob.keystore'
name = 'bob'
public_address = 'HcScjdXXB4zugs6xf7nSJGB338wDk9cqcV8oFwmh6Exotu6setNp4EHkA4mzr9i'

[[dnas]]
file = '/home/holomachine/projects/hUdemy/dna/dist/dna.dna.json'
hash = 'QmP7wJM5Yx72S6yqsUQE5HFo9hMTMG4V8s4Akdbp6qjP6z'
id = 'hc-courses'

[[instances]]
agent = 'hc-alice'
dna = 'hc-courses'
id = 'alice-instance'

[instances.storage]
type = 'memory'

[[interfaces]]
admin = true
id = 'alice-interface'

[[interfaces.instances]]
id = 'alice-instance'

[interfaces.driver]
port = 8888
type = 'websocket'

[[instances]]
agent = 'hc-bob'
dna = 'hc-courses'
id = 'bob-instance'

[instances.storage]
type = 'memory'

[[interfaces]]
admin = true
id = 'bob-interface'

[[interfaces.instances]]
id = 'bob-instance'

[interfaces.driver]
port = 8889
type = 'websocket'

[logger]
state_dump = true
type = 'debug'

[logger.rules]
rules = []

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = false
trace = false
